substitutions:
  name: apollo-msr-2-b32c94
  friendly_name: Bedroom MultiSensor
packages:
  ApolloAutomation.MSR-2: github://ApolloAutomation/MSR-2/Integrations/ESPHome/MSR-2.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: GjgLN0BOuzP3Wy9bXZ9VjIrPdkYJDb0lcqGTFH64IQs=

logger:
  level: DEBUG
wifi:
  ssid: !secret wifi_ssid2
  password: !secret wifi_password
