substitutions:
  name: home-assistant-voice-098de1
  friendly_name: Office Jarvis
packages:
  Nabu Casa.Home Assistant Voice PE: github://esphome/home-assistant-voice-pe/home-assistant-voice.yaml

switch:
  - platform: gpio
    id: grove_port_power
    pin: GPIO46
    restore_mode: ALWAYS_ON

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: bO7PknuSXpaoORiejqcQKzHLGLWsfUkBXL+Ytw93y9g=


wifi:
  ssid: !secret wifi_ssid2
  password: !secret wifi_password

i2c:
  - id: grove_i2c
    sda: GPIO1
    scl: GPIO2
    frequency: 100kHz
    scan: true

sensor:
  - platform: scd4x
    i2c_id: grove_i2c
    co2:
      name: "${friendly_name} CO2"
    temperature:
      id: scd41_temperature
      name: "${friendly_name} Temperature"
    humidity:
      id: scd41_humidity
      name: "${friendly_name} Humidity"
    automatic_self_calibration: true
    update_interval: 60s

#  - platform: sgp4x
#    i2c_id: grove_i2c
#    voc:
#      name: "${friendly_name} VOC Index"
#    nox:
#      name: "${friendly_name} NOx Index"
#    compensation:
#      temperature_source: scd41_temperature
#      humidity_source: scd41_humidity
#    store_baseline: true
#    update_interval: 60s
